### ISSUE TITLE
Add gdstwx.com

### ISSUE THREAD

**Issue by skylarmt** [matomo-org/referrer-spam-blacklist#1105]
I just saw the following URL in my visitor log:

https://www.gdstwx.com/5-seo-tips-to-boost-rankings-in-2019/81901002/

It redirects via google.co.jp and eventually lands on xtrafficplus.com, which is already on the list.

**Comment by matto15** [comment]
Just saw the domain itself gdswtx.com.

**Comment by spmedia** [comment]
Hi,

Please post this as a Pull Request and not an Issue. Thanks!

**Comment by skylarmt** [comment]
> Please post this as a Pull Request and not an Issue

You need to update the readme, this is what is says:

>To add a new referrer spammer to the list, click here to edit the spammers.txt file and select Create a new branch for this commit and start a pull request. **_Alternatively you can create a new issue._**
