### ISSUE TITLE
Non spam in list?

### ISSUE THREAD

**Issue by Zodiac1978** [matomo-org/referrer-spam-blacklist#1144]
Is this really spam?
https://www.100searchengines.com/
https://github.com/matomo-org/referrer-spam-blacklist/blob/master/spammers.txt#L9

Looks like a meta search engine.

Domain is registered in the US:
http://whois.domaintools.com/100searchengines.com

I am not sure if the whole thing of collecting spammy sites is working in general. Domain owner can change and your list is getting invalid and incomplete faster than you can say "Pull Request for each single domain, please". In the same time things have changed and your whole approach is crashing like a house of cards built by a three year old ...

**Comment by spmedia** [comment]
Yes, that particular domain has a history of showing up as referrer spam in the past. For example, it showed up in the stats of a honeypot in 2016, #479

**Comment by Zodiac1978** [comment]
> If you wish to open a PR and dispute any domains you find in the list, feel free to!

No, as I don't think the whole approach is working. We need to find technical solutions to prevent those spam. Collecting single domains is a Sisyphean task and is always a defensive work. I think there have to be an active way of stopping this.
