### ISSUE TITLE
Remove from list vk.com

### ISSUE THREAD

**Issue by abordage** [matomo-org/referrer-spam-blacklist#1194]
This is a social network
https://github.com/matomo-org/searchengine-and-social-list/blob/master/Socials.yml#L247

**Comment by spmedia** [comment]
Hello, that is the part of Matomo that identifies social networks and marks them in your dashboard. 

Yes, VK.com is a RU social network. 

It is **NOT** in the list of spammers @ https://github.com/matomo-org/referrer-spam-blacklist/blob/master/spammers.txt
