### ISSUE TITLE
100searchengines.com should not be listed as referral spam

### ISSUE THREAD

**Issue by GeraldODea** [matomo-org/referrer-spam-blacklist#1211]
I'm the owner of 100searchengines.com and we absolutely do not and never have done referral spam. We are a search engine with results from Google, Bing and Wikipedia. We have no bot or crawler and never had one.

There is a statement from Edmond Major III "Yes, that particular domain has a history of showing up as referrer spam in the past. For example, it showed up in the stats of a honeypot in 2016, #479"  is totally untrue, unless Google or Bing indexed your honeypot, because like I said we use their results.

If you are going to list us, you might as well list our other search engines, searchalot.com and alltheinternet.com because those are search engines as well.   Unless this is fixed I would not recommend any website use this product as it has false positives and they won't fix it.

as an example from 2019, Torsten Landsiedel noticed it was incorrectly added:
https://github.com/matomo-org/referrer-spam-blacklist/issues/1144

and listing 2 doorway pages from dubious blogs, that are probably basing it off of your list:
https://sensorstechforum.com/block-100searchengines-com-referral-traffic/ and https://fatcatstrategies.com/blog/understanding-spam-google-analytics-part-2/
is disingenuous.

Regards,
Gerald O'Dea
Advanced Search Technologies, Inc.

**Comment by spmedia** [comment]
Gerald O'Dea,

Thank you for finding the time to write about this issue. We will remove your website from the list.

**Comment by spmedia** [comment]
This has been completed in #1222.
