### ISSUE TITLE
Add http://127.0.0.1:8888/orange.html

### ISSUE THREAD

**Issue by edbakerguitar** [matomo-org/referrer-spam-blacklist#655]
I've been getting multiple visits per day from this referrer since mid-January, there are a lot of reports online about it appearing on others websites too. (in google analytics mostly, boo!) Please could the following address be added:

http://127.0.0.1:8888/orange.html

Thanks!

Ed

**Comment by spmedia** [comment]
Sorry for the late reply.

Looks like there is a lot of discussion about this exact problem over at https://www.en.advertisercommunity.com/t5/Google-Analytics-Referral-Spam/Unknown-Referral-Source/td-p/1628684#

Should be able to answer any questions you have :)
