### ISSUE TITLE
Several domains per pull request

### ISSUE THREAD

**Issue by kambrium** [matomo-org/referrer-spam-blacklist#693]
I have dozens of spammers in my log and it takes a lot of time to create a new pull request per domain. Would it be possible to include multiple domains per pull request if the "symptoms" are the same (in my case constant HEAD requests, mostly Russian domains, completely unrelated content)?

**Comment by kambrium** [comment]
Hello?

**Comment by spmedia** [comment]
Sure, we can make an exception for this as there seems to be a recent surge of spam.
