### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by gjedeer** [matomo-org/referrer-spam-blacklist#754]
My Websites widget is full of spam domains which are already on this list but Matomo is still using a release from January, which was the last release made here.

**Comment by spmedia** [comment]
Matomo automatically updates the spammers.txt every week regardless of if there is a release or a core update is made.

Can you tell me what version you are using and what domains are showing?

Thanks

**Comment by gjedeer** [comment]
3.4.0 (which was the latest when the ticket was opened) and the domain is zahvat.ru

I've manually updated `vendor/matomo/referrer-spam-blacklist/spammers.txt` after opening that issue because the file was from January - release 1.1.1.

The file has not been automatically updated since then too:
```
/var/www/piwik# ls -l ./vendor/matomo/referrer-spam-blacklist/spammers.txt
-rw-r--r-- 1 www-data www-data 10845 Apr 11 12:10 ./vendor/matomo/referrer-spam-blacklist/spammers.txt
```

After reading some sources I see that `enable_internet_features=1` is required in the config.ini file, my file didn't have this line so there's a chance this is the reason. Very confusing that it's disabled by default.
