### ISSUE TITLE
abc.xyz included?

### ISSUE THREAD

**Issue by rolandinsh** [matomo-org/referrer-spam-blacklist#781]
Any reason to include `abc.xyz`? (Google's Alphabet)
Committed on Nov 22, 2016: https://github.com/matomo-org/referrer-spam-blacklist/commit/667c2dbd4838d5ae2cd16e9368c5d6533c2b3227

**Comment by spmedia** [comment]
Good eye. Removed #784

**Comment by zant95** [comment]
This domain among others has been added again in 8d7f804684decc3f49f88431362d2c815ee9d742.

**Comment by spmedia** [comment]
Gah. That's my bad. Removed (again). Thanks @zant95
